shellEmulator: true

trustPolicy: no-downgrade

packages: []

catalogs:

  build:
    '@intlify/unplugin-vue-i18n': ^11.0.7
    '@shikijs/markdown-it': ^3.23.0
    '@unocss/eslint-config': ^66.6.1
    '@vitejs/plugin-vue': ^6.0.4
    beasties: ^0.4.1
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.59.0
    shiki: ^3.23.0
    unocss: ^66.6.1
    unplugin: ^2.3.11
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^29.2.0
    vite: ^7.3.1
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-pwa: ^1.2.0
    vite-plugin-vue-devtools: ^8.0.6
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.3.0
    vite-ssg-sitemap: ^0.10.0

  dev:
    '@antfu/eslint-config': ^7.6.1
    '@iconify-json/carbon': ^1.2.18
    '@vue-macros/volar': ^3.1.2
    '@vue/test-utils': ^2.4.6
    cypress: ^15.10.0
    cypress-vite: ^1.8.0
    eslint: ^10.0.2
    eslint-plugin-cypress: ^6.1.0
    eslint-plugin-format: ^2.0.1
    https-localhost: ^4.7.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.8.2
    vitest: ^4.0.18
    vue-tsc: ^3.2.5

  frontend:
    '@unhead/vue': ^2.1.7
    '@unocss/reset': ^66.6.1
    '@vueuse/core': ^14.2.1
    nprogress: ^0.2.0
    pinia: ^3.0.4
    vue: ^3.5.29
    vue-i18n: ^11.2.8
    vue-router: ^5.0.3

  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
